### ISSUE TITLE
스크롤바 유무에 따라 레이아웃이 바뀌는 문제

### ISSUE THREAD

**Issue by ucharles** [ucharles/gachatory#78]
## 문제
- 스크롤바 유무에 따라 레이아웃이 작고 커지는 현상 발생

## 해결법
- CSS에서 스크롤바가 항상 존재하도록 설정
``` css
html {
  overflow-y: scroll;
}
```
